name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book-sources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Copy GGR274 Book source files to _publish/ggr directory
      run: make publish-source

    - name: Push _publish/ directory to UofTCompDSci/ggr274-20271
      uses: cpina/github-action-push-to-another-repository@v1.5.1
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: '_publish/'
        destination-github-username: 'UofTCompDSci'
        destination-repository-name: 'ggr274-20271'
        user-email: reid@cs.toronto.edu
        target-branch: main
